In [46]:
import pandas as pd
import pandas as pd

# List of dictionaries format
dat1 = {
    "Department": ["HR", "HR", "IT", "Member", "Member", "Member", "Leader", "Leader", "Sales"],
    "salary":    [50000, 40000, 70000, 40000, 20000, 10000, 90000, 50000, 55000],
    "age":       [40, 35, 30, 21, 20, 28, 40, 20, 32]
}


# Create DataFrame directly
df = pd.DataFrame(dat1)

# Display DataFrame
print(df)

  Department  salary  age
0         HR   50000   40
1         HR   40000   35
2         IT   70000   30
3     Member   40000   21
4     Member   20000   20
5     Member   10000   28
6     Leader   90000   40
7     Leader   50000   20
8      Sales   55000   32

In [57]:
df.groupby("Department")["salary"].mean()
# df.groupby(["Department","age"])["salary"].mean()

Department
HR        45000.000000
IT        70000.000000
Leader    70000.000000
Member    23333.333333
Sales     55000.000000
Name: salary, dtype: float64

In [51]:
df.groupby("Department")["salary"].count()  # com
# df.groupby("Department")["salary"].max()  # com
# df.groupby("Department")["salary"].min()  # give min of salary 
# df.groupby("Department")["age"].min()  # give min of salary

Department
HR        2
IT        1
Leader    2
Member    3
Sales     1
Name: salary, dtype: int64

In [58]:
# we can custom all above function in on line 
df.groupby("Department")["salary"].agg(["mean","max","min","count"])


# we can also give special for all aggregation column 
df.groupby("Department")["salary"].agg(
    avg_sal="mean",high_score="min"
    

)

                 avg_sal  high_score
Department
HR          45000.000000       40000
IT          70000.000000       70000
Leader      70000.000000       50000
Member      23333.333333       10000
Sales       55000.000000       55000

In [62]:
# transform funtion in pandas
df["Higher"]=df.groupby("Department")["salary"].transform("max")
df

  Department  salary  age  Higher
0         HR   50000   40   50000
1         HR   40000   35   50000
2         IT   70000   30   70000
3     Member   40000   21   40000
4     Member   20000   20   40000
5     Member   10000   28   40000
6     Leader   90000   40   90000
7     Leader   50000   20   90000
8      Sales   55000   32   55000

In [64]:
# filter elemnt based on mean,max and etc.
df.groupby("Department").filter(lambda x:x["salary"].mean()>50000)

  Department  salary  age  Higher
2         IT   70000   30   70000
6     Leader   90000   40   90000
7     Leader   50000   20   90000
8      Sales   55000   32   55000