In [52]:
import pandas as pd
data={
  "ID": [1,2,3,4,5,6,7,8,9,10],
    "Name": ["Rahul","Priya","Amit","Neha","Arjun","Meena","Rohan","Anjali","Karan","Sneha"],
    "Age": [24,22,28,26,30,21,27,23,25,29],
    "Gender": ["M","F","M","F","M","F","M","F","M","F"],
    "Hobby": ["Cricket","Dancing","Reading","Painting","Football","Singing","Gaming","Writing","Travelling","Photography"],
    "Salary": [35000,40000,50000,42000,60000,32000,55000,38000,45000,48000],
    "City": ["Lucknow","Mumbai","Delhi","Bhopal","Jaipur","Patna","Bangalore","Hyderabad","Chandigarh","Kolkata"],
    "State": ["UP","MH","DL","MP","RJ","BR","KA","TS","CH","WB"],
    "ShortForm": ["LKO","MUM","DEL","BPL","JPR","PAT","BLR","HYD","CHD","KOL"],
 
}
df= pd.DataFrame(data)
print(df)

   ID    Name  Age Gender        Hobby  Salary        City State ShortForm
0   1   Rahul   24      M      Cricket   35000     Lucknow    UP       LKO
1   2   Priya   22      F      Dancing   40000      Mumbai    MH       MUM
2   3    Amit   28      M      Reading   50000       Delhi    DL       DEL
3   4    Neha   26      F     Painting   42000      Bhopal    MP       BPL
4   5   Arjun   30      M     Football   60000      Jaipur    RJ       JPR
5   6   Meena   21      F      Singing   32000       Patna    BR       PAT
6   7   Rohan   27      M       Gaming   55000   Bangalore    KA       BLR
7   8  Anjali   23      F      Writing   38000   Hyderabad    TS       HYD
8   9   Karan   25      M   Travelling   45000  Chandigarh    CH       CHD
9  10   Sneha   29      F  Photography   48000     Kolkata    WB       KOL

In [54]:
# Renaming column indexing 
df.rename(columns={"City":"Nice City"},inplace=True)
# if inplace is true then orginal DataFrame has been changed
df

# df.rename(index={0:"row1", 1:"row1"})   # row will be chnaged
df

   ID    Name  Age Gender        Hobby  Salary   Nice City State ShortForm
0   1   Rahul   24      M      Cricket   35000     Lucknow    UP       LKO
1   2   Priya   22      F      Dancing   40000      Mumbai    MH       MUM
2   3    Amit   28      M      Reading   50000       Delhi    DL       DEL
3   4    Neha   26      F     Painting   42000      Bhopal    MP       BPL
4   5   Arjun   30      M     Football   60000      Jaipur    RJ       JPR
5   6   Meena   21      F      Singing   32000       Patna    BR       PAT
6   7   Rohan   27      M       Gaming   55000   Bangalore    KA       BLR
7   8  Anjali   23      F      Writing   38000   Hyderabad    TS       HYD
8   9   Karan   25      M   Travelling   45000  Chandigarh    CH       CHD
9  10   Sneha   29      F  Photography   48000     Kolkata    WB       KOL

In [50]:
# Changing column order 
# df= df[["Age","Name","Hobby","City"]]  # set column ordering
df

# move 1 column to the fornt like this 
cols = ["Name"] + [ col for col in df.columns if col!="Name"]
df=df[cols]
df

   ID    Name  Age Gender        Hobby  Salary        City State ShortForm
0   1   Rahul   24      M      Cricket   35000     Lucknow    UP       LKO
1   2   Priya   22      F      Dancing   40000      Mumbai    MH       MUM
2   3    Amit   28      M      Reading   50000       Delhi    DL       DEL
3   4    Neha   26      F     Painting   42000      Bhopal    MP       BPL
4   5   Arjun   30      M     Football   60000      Jaipur    RJ       JPR
5   6   Meena   21      F      Singing   32000       Patna    BR       PAT
6   7   Rohan   27      M       Gaming   55000   Bangalore    KA       BLR
7   8  Anjali   23      F      Writing   38000   Hyderabad    TS       HYD
8   9   Karan   25      M   Travelling   45000  Chandigarh    CH       CHD
9  10   Sneha   29      F  Photography   48000     Kolkata    WB       KOL